### ISSUE TITLE
Questions regarding the WSI magnification

### ISSUE THREAD

**Issue by pxliang** [Hanminghao/MSCPT#3]
Thank you for the amazing work!

I have a question regarding the WSI magnifications used in the paper. You mentioned that you used CLAM to extract patches, did you use patch_level =1 for 20X magnification? How about 5x magnification? Which patch_level did you use?

**Comment by Hanminghao** [comment]
Thank you for your attention. I made minor modifications to CLAM. Since not all WSIs have the option for 20X magnification, I typically crop 256×256 patches from WSIs that do have the 20X option. For WSIs without the 20X option, I crop 512×512 patches at 40X magnification and then resize them to 256×256. The processing for 5X magnification patches is similar; they are cropped at 10X magnification and then resized.

**Comment by CV-ZhangXin** [comment]
@pxliang Hello, did you solve this problem? How do you get the features at different magnifications?

**Comment by CV-ZhangXin** [comment]
@pxliang Hello, did you solve this problem? How do you get the features at different magnifications?
