### ISSUE TITLE
generating descriptions for each category using GPT

### ISSUE THREAD

**Issue by Luan-zb** [Hanminghao/MSCPT#4]
Hello, could you please provide the code to start generating descriptions for each category using GPT? It appears that the descriptions generated by other code are stored in the /train_data/GPT-4/description/{args.dataset_name}.json file. Thank you!

**Comment by Hanminghao** [comment]
Thank you for your attention. Since our requests to large language models are infrequent, we do not employ APIs for generating pathology visual descriptions. Instead, we manually query the corresponding LLM and compile the responses into the respective JSON file. The descriptions that have been generated can be found in [this link](https://github.com/Hanminghao/MSCPT/tree/master/train_data).

**Comment by Luan-zb** [comment]
> Thank you for your attention. Since our requests to large language models are infrequent, we do not employ APIs for generating pathology visual descriptions. Instead, we manually query the corresponding LLM and compile the responses into the respective JSON file. The descriptions that have been generated can be found in [this link](https://github.com/Hanminghao/MSCPT/tree/master/train_data).

Could you please tell me which LLM you are using for querying? Could you also provide an access link and instructions on how to query it?

**Comment by Luan-zb** [comment]
Could you please tell me which LLM you are using for querying? Could you also provide an access link and instructions on how to query it?

**Comment by Hanminghao** [comment]
In the final version, we utilized GPT-4 to generate pathological visual descriptions. In the ablation experiments, we compared Gemini-1.5-pro, Claude-3, Llama-3, and GPT-3.5, with all inquiries conducted on the official websites of the respective LLMs. For specific inquiry methods, please refer to Section Ⅲ.C.
